#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:3.3.0-preview1

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          script:
            - bundle install
            - bundle exec rake
      - step:
          name: Lint code
          script:
            - ruby -wc **/*.rb
